DATA:
    ROOT: ''
    TRAIN_FILE: '../datasets/kinetics-dataset/k400_resized_1/annotations_svt/train.csv'
    VAL_FILE: '../datasets/kinetics-dataset/k400_resized_1/annotations_svt/val.csv'
    DATASET: kinetics400
    NUM_FRAMES: 8
    NUM_CLASSES: 400
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
    BATCH_SIZE: 8
MODEL:
  TYPE: videofocalnet_tiny
  NAME: video-focalnet_tiny
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 400
  FOCAL:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    FOCAL_LEVELS: [2, 2, 2, 2]
    FOCAL_WINDOWS: [3, 3, 3, 3]
  LABEL_SMOOTHING: 0.1
TRAIN:
  BASE_LR: 0.1
  WARMUP_LR: 0.001
  MIN_LR: 0.001
  EPOCHS: 120
  WEIGHT_DECAY: 1e-4
  OPTIMIZER:
    NAME: "sgd"
  WARMUP_EPOCHS: 20
  PRETRAINED_PATH: './pretrained/focalnet_tiny_srf.pth'
AUG:
  FRAME_INTERVAL: 4
  FLIP_RATIO: 0.5
  COLOR_JITTER: 0.8
  GRAY_SCALE: 0.2
  MIXUP: 0.8
  MIXUP_PROB: 0.5
SAVE_FREQ: 10